// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl             string   `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cat) Reset()         { *m = Cat{} }
func (m *Cat) String() string { return proto.CompactTextString(m) }
func (*Cat) ProtoMessage()    {}
func (*Cat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{0}
}

func (m *Cat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cat.Unmarshal(m, b)
}
func (m *Cat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cat.Marshal(b, m, deterministic)
}
func (m *Cat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cat.Merge(m, src)
}
func (m *Cat) XXX_Size() int {
	return xxx_messageInfo_Cat.Size(m)
}
func (m *Cat) XXX_DiscardUnknown() {
	xxx_messageInfo_Cat.DiscardUnknown(m)
}

var xxx_messageInfo_Cat proto.InternalMessageInfo

func (m *Cat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cat) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type ListCatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCatsRequest) Reset()         { *m = ListCatsRequest{} }
func (m *ListCatsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCatsRequest) ProtoMessage()    {}
func (*ListCatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{1}
}

func (m *ListCatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCatsRequest.Unmarshal(m, b)
}
func (m *ListCatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCatsRequest.Marshal(b, m, deterministic)
}
func (m *ListCatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCatsRequest.Merge(m, src)
}
func (m *ListCatsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCatsRequest.Size(m)
}
func (m *ListCatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCatsRequest proto.InternalMessageInfo

type ListCatsResponse struct {
	Cats                 []*Cat   `protobuf:"bytes,1,rep,name=cats,proto3" json:"cats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCatsResponse) Reset()         { *m = ListCatsResponse{} }
func (m *ListCatsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCatsResponse) ProtoMessage()    {}
func (*ListCatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{2}
}

func (m *ListCatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCatsResponse.Unmarshal(m, b)
}
func (m *ListCatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCatsResponse.Marshal(b, m, deterministic)
}
func (m *ListCatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCatsResponse.Merge(m, src)
}
func (m *ListCatsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCatsResponse.Size(m)
}
func (m *ListCatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCatsResponse proto.InternalMessageInfo

func (m *ListCatsResponse) GetCats() []*Cat {
	if m != nil {
		return m.Cats
	}
	return nil
}

type GetFeaturedCatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeaturedCatsRequest) Reset()         { *m = GetFeaturedCatsRequest{} }
func (m *GetFeaturedCatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeaturedCatsRequest) ProtoMessage()    {}
func (*GetFeaturedCatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{3}
}

func (m *GetFeaturedCatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeaturedCatsRequest.Unmarshal(m, b)
}
func (m *GetFeaturedCatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeaturedCatsRequest.Marshal(b, m, deterministic)
}
func (m *GetFeaturedCatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeaturedCatsRequest.Merge(m, src)
}
func (m *GetFeaturedCatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeaturedCatsRequest.Size(m)
}
func (m *GetFeaturedCatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeaturedCatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeaturedCatsRequest proto.InternalMessageInfo

type GetFeaturedCatsResponse struct {
	Cats                 []*Cat   `protobuf:"bytes,1,rep,name=cats,proto3" json:"cats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeaturedCatsResponse) Reset()         { *m = GetFeaturedCatsResponse{} }
func (m *GetFeaturedCatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeaturedCatsResponse) ProtoMessage()    {}
func (*GetFeaturedCatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{4}
}

func (m *GetFeaturedCatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeaturedCatsResponse.Unmarshal(m, b)
}
func (m *GetFeaturedCatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeaturedCatsResponse.Marshal(b, m, deterministic)
}
func (m *GetFeaturedCatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeaturedCatsResponse.Merge(m, src)
}
func (m *GetFeaturedCatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeaturedCatsResponse.Size(m)
}
func (m *GetFeaturedCatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeaturedCatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeaturedCatsResponse proto.InternalMessageInfo

func (m *GetFeaturedCatsResponse) GetCats() []*Cat {
	if m != nil {
		return m.Cats
	}
	return nil
}

type CreateCatRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCatRequest) Reset()         { *m = CreateCatRequest{} }
func (m *CreateCatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCatRequest) ProtoMessage()    {}
func (*CreateCatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{5}
}

func (m *CreateCatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCatRequest.Unmarshal(m, b)
}
func (m *CreateCatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCatRequest.Marshal(b, m, deterministic)
}
func (m *CreateCatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCatRequest.Merge(m, src)
}
func (m *CreateCatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCatRequest.Size(m)
}
func (m *CreateCatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCatRequest proto.InternalMessageInfo

func (m *CreateCatRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{6}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

type GetUserResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{7}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Cat)(nil), "catcollection.api.v1.Cat")
	proto.RegisterType((*ListCatsRequest)(nil), "catcollection.api.v1.ListCatsRequest")
	proto.RegisterType((*ListCatsResponse)(nil), "catcollection.api.v1.ListCatsResponse")
	proto.RegisterType((*GetFeaturedCatsRequest)(nil), "catcollection.api.v1.GetFeaturedCatsRequest")
	proto.RegisterType((*GetFeaturedCatsResponse)(nil), "catcollection.api.v1.GetFeaturedCatsResponse")
	proto.RegisterType((*CreateCatRequest)(nil), "catcollection.api.v1.CreateCatRequest")
	proto.RegisterType((*GetUserRequest)(nil), "catcollection.api.v1.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "catcollection.api.v1.GetUserResponse")
}

func init() { proto.RegisterFile("api/v1/api.proto", fileDescriptor_1dfa6b8f70674874) }

var fileDescriptor_1dfa6b8f70674874 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcf, 0x8f, 0xd2, 0x50,
	0x10, 0x06, 0x41, 0x85, 0x31, 0x91, 0xfa, 0x42, 0xb4, 0xd6, 0x0b, 0x69, 0x04, 0x39, 0x48, 0x1b,
	0x30, 0xf1, 0xe2, 0x49, 0x6a, 0xc4, 0x83, 0x07, 0x83, 0x21, 0x31, 0xee, 0x61, 0x33, 0x94, 0x09,
	0xbc, 0x4d, 0xdb, 0xd7, 0x7d, 0x6f, 0xca, 0xbf, 0xb0, 0xff, 0xf6, 0x86, 0x96, 0x5f, 0x61, 0x4b,
	0xd8, 0xec, 0xad, 0xfd, 0xe6, 0x9b, 0xf9, 0xbe, 0xf7, 0x4d, 0x06, 0x2c, 0x4c, 0xa5, 0xbf, 0x1e,
	0xfa, 0x98, 0x4a, 0x2f, 0xd5, 0x8a, 0x95, 0x68, 0x87, 0xc8, 0xa1, 0x8a, 0x22, 0x0a, 0x59, 0xaa,
	0xc4, 0xdb, 0x14, 0xd6, 0x43, 0xf7, 0x2b, 0xd4, 0x02, 0x64, 0x21, 0xa0, 0x9e, 0x60, 0x4c, 0x76,
	0xb5, 0x53, 0xed, 0x37, 0xa7, 0xf9, 0xb7, 0xf8, 0x00, 0x4d, 0x19, 0xe3, 0x92, 0xae, 0x33, 0x1d,
	0xd9, 0xcf, 0xf2, 0x42, 0x23, 0x07, 0x66, 0x3a, 0x72, 0xdf, 0x40, 0xeb, 0xb7, 0x34, 0x1c, 0x20,
	0x9b, 0x29, 0xdd, 0x66, 0x64, 0xd8, 0xfd, 0x0e, 0xd6, 0x01, 0x32, 0xa9, 0x4a, 0x0c, 0x89, 0x01,
	0xd4, 0x43, 0x64, 0x63, 0x57, 0x3b, 0xb5, 0xfe, 0xab, 0xd1, 0x7b, 0xaf, 0xcc, 0x83, 0x17, 0x20,
	0x4f, 0x73, 0x9a, 0x6b, 0xc3, 0xdb, 0x09, 0xf1, 0x4f, 0x42, 0xce, 0x34, 0x2d, 0x8e, 0x87, 0xff,
	0x82, 0x77, 0x0f, 0x2a, 0x4f, 0xd3, 0xe8, 0x81, 0x15, 0x68, 0x42, 0xa6, 0x0d, 0x54, 0x4c, 0x2f,
	0x7b, 0xbe, 0x6b, 0xc1, 0xeb, 0x09, 0xf1, 0xcc, 0x90, 0xde, 0x79, 0xf8, 0x04, 0xad, 0x3d, 0xb2,
	0xd5, 0x6e, 0xc3, 0x73, 0x8a, 0x51, 0x46, 0xdb, 0xce, 0xe2, 0x67, 0x74, 0x57, 0x03, 0x08, 0x90,
	0xff, 0x92, 0x5e, 0xcb, 0x90, 0xc4, 0x15, 0x34, 0x76, 0xc1, 0x88, 0x6e, 0xb9, 0xbd, 0x93, 0x2c,
	0x9d, 0xde, 0x25, 0x5a, 0xa1, 0xef, 0x56, 0x44, 0x9a, 0x9b, 0x3a, 0x0e, 0x46, 0x7c, 0x2e, 0x6f,
	0x2e, 0x4f, 0xd6, 0x19, 0x3c, 0x92, 0xbd, 0x57, 0xfc, 0x03, 0xcd, 0x7d, 0x80, 0xe2, 0x8c, 0xd1,
	0xd3, 0x84, 0x9d, 0xf3, 0x6b, 0x71, 0x2b, 0xe2, 0x1f, 0xbc, 0xdc, 0x06, 0x2b, 0x3e, 0x9e, 0x75,
	0x73, 0xb4, 0x09, 0xa7, 0x7b, 0x81, 0xb5, 0xf3, 0x3a, 0xfe, 0xf1, 0x7f, 0xbc, 0x94, 0xbc, 0xca,
	0xe6, 0x5e, 0xa8, 0x62, 0xff, 0x46, 0xad, 0x30, 0x99, 0x6b, 0x4c, 0x16, 0x2b, 0xa5, 0x0d, 0xfb,
	0x21, 0xf2, 0xe0, 0x30, 0xc5, 0x37, 0xc5, 0xbe, 0xfc, 0xfc, 0x5e, 0xfc, 0xe2, 0x80, 0xbe, 0x61,
	0x2a, 0xe7, 0x2f, 0x72, 0xe4, 0xcb, 0x7d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xa7, 0xb3, 0x25,
	0x55, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatServiceClient is the client API for CatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatServiceClient interface {
	ListCats(ctx context.Context, in *ListCatsRequest, opts ...grpc.CallOption) (*ListCatsResponse, error)
	GetFeaturedCats(ctx context.Context, in *GetFeaturedCatsRequest, opts ...grpc.CallOption) (*GetFeaturedCatsResponse, error)
	CreateCat(ctx context.Context, in *CreateCatRequest, opts ...grpc.CallOption) (*Cat, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type catServiceClient struct {
	cc *grpc.ClientConn
}

func NewCatServiceClient(cc *grpc.ClientConn) CatServiceClient {
	return &catServiceClient{cc}
}

func (c *catServiceClient) ListCats(ctx context.Context, in *ListCatsRequest, opts ...grpc.CallOption) (*ListCatsResponse, error) {
	out := new(ListCatsResponse)
	err := c.cc.Invoke(ctx, "/catcollection.api.v1.CatService/ListCats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetFeaturedCats(ctx context.Context, in *GetFeaturedCatsRequest, opts ...grpc.CallOption) (*GetFeaturedCatsResponse, error) {
	out := new(GetFeaturedCatsResponse)
	err := c.cc.Invoke(ctx, "/catcollection.api.v1.CatService/GetFeaturedCats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CreateCat(ctx context.Context, in *CreateCatRequest, opts ...grpc.CallOption) (*Cat, error) {
	out := new(Cat)
	err := c.cc.Invoke(ctx, "/catcollection.api.v1.CatService/CreateCat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/catcollection.api.v1.CatService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServiceServer is the server API for CatService service.
type CatServiceServer interface {
	ListCats(context.Context, *ListCatsRequest) (*ListCatsResponse, error)
	GetFeaturedCats(context.Context, *GetFeaturedCatsRequest) (*GetFeaturedCatsResponse, error)
	CreateCat(context.Context, *CreateCatRequest) (*Cat, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

// UnimplementedCatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCatServiceServer struct {
}

func (*UnimplementedCatServiceServer) ListCats(ctx context.Context, req *ListCatsRequest) (*ListCatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCats not implemented")
}
func (*UnimplementedCatServiceServer) GetFeaturedCats(ctx context.Context, req *GetFeaturedCatsRequest) (*GetFeaturedCatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeaturedCats not implemented")
}
func (*UnimplementedCatServiceServer) CreateCat(ctx context.Context, req *CreateCatRequest) (*Cat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCat not implemented")
}
func (*UnimplementedCatServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterCatServiceServer(s *grpc.Server, srv CatServiceServer) {
	s.RegisterService(&_CatService_serviceDesc, srv)
}

func _CatService_ListCats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListCats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catcollection.api.v1.CatService/ListCats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListCats(ctx, req.(*ListCatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetFeaturedCats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeaturedCatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetFeaturedCats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catcollection.api.v1.CatService/GetFeaturedCats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetFeaturedCats(ctx, req.(*GetFeaturedCatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catcollection.api.v1.CatService/CreateCat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CreateCat(ctx, req.(*CreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catcollection.api.v1.CatService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catcollection.api.v1.CatService",
	HandlerType: (*CatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCats",
			Handler:    _CatService_ListCats_Handler,
		},
		{
			MethodName: "GetFeaturedCats",
			Handler:    _CatService_GetFeaturedCats_Handler,
		},
		{
			MethodName: "CreateCat",
			Handler:    _CatService_CreateCat_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _CatService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/api.proto",
}
